### ISSUE TITLE
在跳转的时候设置addToBackStack=false不添加到用户操作栈中

### ISSUE THREAD

**Issue by qq570026938** [xuexiangjys/XPage#11]
在跳转的时候设置addToBackStack=false不添加到用户操作栈中，我在多次跳转的后，点击返回，发现onDestroy（）方法走了多次，感觉是每次跳转都是创建了个新fragment，请问可不可以，在创建新fragment时候销毁之前的fragment，而不单单是不加入操作栈

**Comment by xuexiangjys** [comment]
使用openPage方法,其本质就是每次跳转就是创建一个新的fragment.你如果每次跳转不希望创建一个新的fragment,建议使用changePage方法.
