### ISSUE TITLE
混淆后  PageLog: Page:xxxxxfragment  is null

### ISSUE THREAD

**Issue by qq570026938** [xuexiangjys/XPage#12]
开启混淆  PageLog: Page:xxxxxfragment  is null  报错找不到对应的fragment是为啥

**Comment by xuexiangjys** [comment]
你难道不知道fragment是不能被混淆的吗?

**Comment by qq570026938** [comment]
> 你难道不知道fragment是不能被混淆的吗?

fragment混淆配置上了，但是还是找不到，我把xpage框架里面的pageinfo 配置上才能用了，我看你demo 没配置pageinfo 也能用感觉很奇怪

**Comment by xuexiangjys** [comment]
pageinfo 实现了Serializable 接口，本来就不需要混淆，你还是自己再好好看吧
