### ISSUE TITLE
编译出现资源链接错误导致编译失败

### ISSUE THREAD

**Issue by anbuqi** [xuexiangjys/XPage#14]
编译出现以下错误
AAPT: D:\AndroidProjects\demo\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:10961: error: resource attr/xui_orientation (aka com.anbuqi.app:attr/xui_orientation) not found.
error: failed linking references.

**Comment by xuexiangjys** [comment]
这个XUI的问题，麻烦你把xui升级到最新版本再用，谢谢
