### ISSUE TITLE
自动配置，找不到AppPageConfig

### ISSUE THREAD

**Issue by Elex92** [xuexiangjys/XPage#15]
错误: 找不到符号
                    return AppPageConfig.getInstance().getPages();
                           ^
  符号:   变量 AppPageConfig
  位置: 类 ApplicationLoader

**Comment by xuexiangjys** [comment]
文档仔细看行不行？
https://github.com/xuexiangjys/XPage#222application%E4%B8%AD%E5%8A%A8%E6%80%81%E6%B3%A8%E5%86%8C%E6%8E%A8%E8%8D%90

**Comment by littlecurl** [comment]
> 错误: 找不到符号
> return AppPageConfig.getInstance().getPages();
> ^
> 符号: 变量 AppPageConfig
> 位置: 类 ApplicationLoader

出现这个问题会有两种情况：
1、没有使用@Page进行注释 XPageFragment 的子类（基本不会，因为大多数人用这个框架就是奔着这个注解去的）

2、没有配好依赖：
文档中说这个 AppPageConfig 是编译时生成的，进去Demo的AppPageConfig 源码，看到类注释里有说这个类是 PageConfigProcessor 生成的，追踪到 PageConfigProcessor 类的包位置，就是“com.github.xuexiangjys.XPage:xpage-compiler”。
如果没有产出，那很有可能就是引对依赖。

而且文档中特意强调了如果使用了kotlin需要切换成kotlin的编译方式。

【注意】如果你使用的是kotlin，请使用如下配置:

apply plugin: 'kotlin-kapt'

dependencies {
  ...
  //XPage
  implementation 'com.github.xuexiangjys.XPage:xpage-lib:3.0.0'
  kapt 'com.github.xuexiangjys.XPage:xpage-compiler:3.0.0'
  //ButterKnife的sdk
  implementation 'com.jakewharton:butterknife:10.1.0'
  kapt 'com.jakewharton:butterknife-compiler:10.1.0'
}


其实就是 annotationProcessor 换成 kapt 

最后，
建议老薛把这两点，关联在一起，列出来，有些人（比如我），一开始使用确实很难同时想到这两点的关系。[/笑哭]

**Comment by xuexiangjys** [comment]
已经加上注释了
