### ISSUE TITLE
openPage无效

### ISSUE THREAD

**Issue by Elex92** [xuexiangjys/XPage#16]
您好！我openPage不知道为什么没有反应。BaseActivity extends XPageActivity
public class MainActivity extends BaseActivity implements  ClickUtils.OnClick2ExitListener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        openPage(MainFragment.class,getIntent().getExtras());

    }

**Comment by xuexiangjys** [comment]
菜鸟不会用，我建议你还是先拿模板工程练练手好了：
https://github.com/xuexiangjys/TemplateSimpleProject

**Comment by Elex92** [comment]
![image](https://user-images.githubusercontent.com/16713043/90336520-f868c080-e00e-11ea-949a-14525ec05564.png)
断点zhi至此，发现是页面对象序列化少了两个参数，才导致openPage无效报错

**Comment by Elex92** [comment]
![1597587805832](https://user-images.githubusercontent.com/16713043/90336553-336af400-e00f-11ea-9141-4cd015e6cb7f.jpg)
