### ISSUE TITLE
Xpage是否可以用注解代替继承,而非继承XpageFragment和XpageActivity来openPage?

### ISSUE THREAD

**Issue by yangjieK** [xuexiangjys/XPage#17]
用继承入侵太强了,例如 项目基类fragment是无法继承你的该类的

**Comment by xuexiangjys** [comment]
XPage的定位是方便使用，并且其本身也是使用了注解，使用继承完全只是为了方便使用。
再说XPageFragment和XPageActivity完全可以替代Activity和Fragment，就像AppCompatActivity一样。
最后，如果你觉得入侵太强，可以使用google的navigation，完全没必要用本框架。
所以，在提意见前，务必首先理解框架设计的初衷和意图，不要想当然。
