### ISSUE TITLE
fragment返回键可以拦截吗？

### ISSUE THREAD

**Issue by yanpengqing** [xuexiangjys/XPage#19]
赞一个，很好很强大。
有个问题，
请问是否可以指定某个fragment拦截返回键或者边缘手势？

**Comment by yanpengqing** [comment]
刚下载demo看了
可以自定义有个Activity, 禁止返回键。

**Comment by xuexiangjys** [comment]
可以的,默认都是fragment先进行处理的.
fragment重写onKeyDown方法就可以了
