### ISSUE TITLE
可以考虑 移除 XPageFragment 中的 ButterKnife 

### ISSUE THREAD

**Issue by thisfeng** [xuexiangjys/XPage#23]
onCreateView 强迫症看到黄油刀，趋势来看 AS 不建议使用黄油刀，可以考虑 移除 ，推荐使用 DataBinding 方式 更为舒适 哈哈，个人见解。当然很多老项目，都是黄油刀，懒得修改。最新新项目正在筹备使用阁下一系列的优秀库    good

**Comment by chengyiqun** [comment]
+1, 等以后安卓开发工具再升级后, 黄油刀恐怕彻底不能用.

**Comment by zimolab** [comment]
确实，我用XFragment的时候发现ViewBinding不起作用，必须重写了onCreateView()方法才行。

@Page(anim = CoreAnim.none)
class HomeFragment : XPageFragment() {
    val binding: FragmentHomeBinding by lazy {
        FragmentHomeBinding.inflate(layoutInflater)
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        mRootView = binding.root
        mUnbinder = null
        initArgs()
        initPage()
        return mRootView
    }
    ......
    /**
     * 初始化控件
     */
    override fun initViews() {
       binding.tvNum.text = "Hello"
    }
    ......
}

**Comment by xuexiangjys** [comment]
将在3.3.0版本去除

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XPage/releases/tag/3.3.0
