### ISSUE TITLE
怎么判断当前fragment是否在栈顶？

### ISSUE THREAD

**Issue by yanpengqing** [xuexiangjys/XPage#24]
RT
栈里面有两个name一样的Fragment，一个是详情页一个是编辑页，我共用的同一个Fragment。
现在有个消息一发送两个界面都收到了消息，我想在当前页面只收到一次消息，需要判断当前Fragment是否是在栈顶，通过name去查找好像不行，换句话说就是得找到栈顶Fragment的实例，比较当前Fragment的实例是否相等。
该如何判断？

**Comment by xuexiangjys** [comment]
不建议使用两个name一样的Fragment!
