### ISSUE TITLE
是否可以在栈内获取到 其它 fragment 对象使用？

### ISSUE THREAD

**Issue by thisfeng** [xuexiangjys/XPage#27]
在使用中发现，很多时候需要在同级别Fragment中 如何去获取其它的fragment对象使用？
只能通过获取当前Fragment所 Attach 的宿主 Activity 再去getPage() 依次按层级获取么？ 

我的层级是
```
MainActivity内
     MainViewPagerFragment 
             --> A1Fragment     
                     ---> 打开了Test3Fragment （页面中要获取A1Fragment对象的情况，可否直接有方法拿到栈内其它对象）
             --> B2Fragment
```
是否可以像 Fragmention  那样有获取同级别栈内的fragment 对象？

**Comment by hakulatata** [comment]
同问，getParentFragment()为空，我是子frag 要获取父类frag 的公用方法 ，getpage ()方法没有找到，getparentfragment 为空

**Comment by xuexiangjys** [comment]
无论怎样,都必须要通过宿主 Activity去获取fragment对象
具体可以参照我的这个提交:
https://github.com/xuexiangjys/XPage/commit/e4808e4cc47e4307a7623526c73b2abb26909e3d
