### ISSUE TITLE
xpage 的onPause() 方法为什么没有走到呢？

### ISSUE THREAD

**Issue by 382202771** [xuexiangjys/XPage#3]
我引入百度地图放到fragment中，其中生命周期onPause()方法没有走到，现在地图首次打开没有问题，切换页面后地图无法缩放移动等，打印日志后看到onPause()方法没有走，请帮我看看，谢谢！

**Comment by xuexiangjys** [comment]
首先，很感谢你提出的问题。
我在排查问题的时候，发现了2个问题：
* fragment切换的时候，每次都是new的新的fragment并进行加载的，可能会导致页面数据不一致以及资源浪费的问题。
* 因为容器只有一个，所以切换的时候没使用replace，而是使用的add + show + hide，所以每次切换并不会走到fragment的onResume和onPause，建议使用onHiddenChanged代替。

目前已修复以上问题，请更新最新版本2.2.3

**Comment by 382202771** [comment]
非常感谢及时的回复  我已经使用了onHiddenChanged 代替 

@Override
public void onHiddenChanged(boolean hidden) {
   super.onHiddenChanged(hidden);
   if(hidden){//不在最前端界面显示，相当于调用了onPause()
      Log.i("123", "onHiddenChanged: 111");
      mGovMapDataMap.onPause();
   }else{//重新显示到最前端 ,相当于调用了onResume()

      Log.i("123", "onHiddenChanged: 222");
   }

}
这样会走到onpause方法  可是我的问题还是依旧  不知道是不是跟百度的api结合有冲突  总之问题还是再次切回到百度地图的时候无法进行移动和缩放操作，还麻烦你再帮我看看是哪里的问题

我先更新下版本看看 谢谢 ！

**Comment by 382202771** [comment]
问题依旧  实在不行我就得把这个有地图这个fragment用activity了  谢谢你的回复
