### ISSUE TITLE
如果使用了setNewActivity(true)，该如何获取返回页面的数据呢？

### ISSUE THREAD

**Issue by zhengwei-D** [xuexiangjys/XPage#31]
看到了throw new SecurityException("You can not call 'openPageForResult' method when you set 'isNewActivity' is true. " +
                            "Because the two pages are not in the same activity, the status of fragment will be wrong!");

那么请问有没有什么解决方案？

**Comment by xuexiangjys** [comment]
可以使用eventbus这类的工具
