### ISSUE TITLE
新建个 DialogFragment 都能报错, 这库真垃圾

### ISSUE THREAD

**Issue by dazeGitHub** [xuexiangjys/XPage#32]
注: XPage::Compiler The user has configuration the module name, it was [app]
注: XPage::Compiler >>> PageConfigProcessor init. <<<
注: XPage::Compiler >>> Found Pages, start... <<<
注: XPage::Compiler >>> Found Pages, size is 145 <<<
注: XPage::Compiler >>> Found Fragment Page: com.smartcity.business.core.webview.XPageWebViewFragment <<<
注: XRouter::Compiler >>> Generated root map, name is : XRouter$$Root$$app <<<
E:\Projects\SmartCityBusiness\app\src\main\java\com\smartcity\business\widget\dialogfragment\SelectCityDialogFragment2.java:5: 错误: 找不到符号
public class SelectCityDialogFragment2 extends BaseDialogFragment{
                                               ^
  符号: 类 BaseDialogFragment
注: E:\Projects\SmartCityBusiness\app\src\main\java\com\smartcity\business\core\http\ExceptionHelper.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个错误

package com.smartcity.business.widget.dialogfragment;

import com.smartcity.business.R;

public class SelectCityDialogFragment2 extends BaseDialogFragment{

    @Override
    public int getLayout() {
        return R.layout.dlg_fragment_select_city;
    }

    @Override
    protected void initView() {

    }
}

**Comment by xuexiangjys** [comment]
你是不是哪里有毛病? 自己垃圾就不要丢人显眼!
