### ISSUE TITLE
我服了，我个 DialogFragment 都需要添加 @Page() 注解，这库真完蛋

### ISSUE THREAD

**Issue by dazeGitHub** [xuexiangjys/XPage#33]
我随便写个Fragment 都需要加这个注解，不加就崩溃，真行啊，跳转不了就跳转不了呗，打个日志就得了呗，凭啥让我所有的 Fragment 都加这个注解？不觉得管的太宽了吗？这是一个正经的第三方库该管的事吗？现在好了，这项目不用这个库都不行了，我是真服气

**Comment by xuexiangjys** [comment]
就你这样，我求你别用，真的

**Comment by dazeGitHub** [comment]
对，我是坏蛋，哈哈哈，我也没想用，新公司的项目在用
