### ISSUE TITLE
Fragment跳转报错

### ISSUE THREAD

**Issue by Eason-shu** [xuexiangjys/XPage#35]
![image](https://github.com/xuexiangjys/XPage/assets/71616046/31388bf3-40ec-4751-a3ac-d9a0b2d658ef)
在进行Fragment的跳转是发生了这个错误？不知道啥原因，我猜想是主容器的问题，于是我换了容器，但是还是报错
![image](https://github.com/xuexiangjys/XPage/assets/71616046/1078e537-49c6-43f3-bc1f-8a34a20a3184)

**Comment by xuexiangjys** [comment]
1.首先,任何作为容器activity的,都需要注册在AndroidManifest里面,这个是基本常识,不懂请自行百度.
2.其次,任何作为容器activity的,都必须在布局中包含id`fragment_container`。这些都是写在文档里的,你不看怪谁?
https://github.com/xuexiangjys/XPage#27%E5%A4%8D%E6%9D%82activity%E7%95%8C%E9%9D%A2%E5%AE%B9%E5%99%A8%E7%9A%84%E8%87%AA%E5%AE%9A%E4%B9%89
