### ISSUE TITLE
startActivityForResult有问题

### ISSUE THREAD

**Issue by tanghb** [xuexiangjys/XPage#37]
不明白你为什么要加 if (this.getPackageManager().resolveActivity(intent, 65536) != null) 判断，这样会导致调用系统的activity时出问题

**Comment by xuexiangjys** [comment]
这样做的原因是:
要检查Intent是否有应用可以处理，需要调用intent的resolveActivity 如果返回值不会null 则可以发送此intent给目标组建。如果不检查，并且设备上面没有任何可以处理此intent的组建，则会引起崩溃

**Comment by tanghb** [comment]
我觉得崩溃是使用方的问题，而不应该由框架进行处理，你这样会影响框架的使用范围，有些场景就是需要使用非注册的目标itent

**Comment by tanghb** [comment]
我现在只能fork一份自己来改了，还是希望框架这块可以放开这块限制
