### ISSUE TITLE
大佬能配置fragment转场动画吗？共享元素

### ISSUE THREAD

**Issue by INTKILOW** [xuexiangjys/XPage#7]
大佬能配置fragment转场动画吗？共享元素

**Comment by xuexiangjys** [comment]
可以配置，具体看文档，里面有写

**Comment by INTKILOW** [comment]
**文档中只有这几种动画**
没有动画
由下到上动画
从左到右动画
渐变
放大
我看你源码里面没有这种形式的动画 
(.addSharedElement(View,String) )
**https://hexiangyuan.github.io/2017/03/08/Android%E5%85%B1%E4%BA%AB%E5%85%83%E7%B4%A0%E8%BD%AC%E5%9C%BA%E5%8A%A8%E7%94%BBPart2%E2%80%94%E2%80%94Fragment%20to%20Fragment/**
