### ISSUE TITLE
中间页面setAddToBackStack设置为false时，不能按照正常页面回退

### ISSUE THREAD

**Issue by lreal** [xuexiangjys/XPage#9]
目前有三个页面，ABC，启动展示A页面，A->B,正常跳转，B->C 跳转时设置setAddToBackStack(false)，此时点击返回键出现以下问题：
问题一、第一次点击返回无响应
问题二、第二次点击直接退出程序

**Comment by xuexiangjys** [comment]
首先需要说明的是，对于一个Activity容器内，要么跳转时都设置setAddToBackStack(false)，要么都不设置。如果像你这样一会儿设置setAddToBackStack(false)，一会儿不设置的话，Activity里的堆栈会错乱，具体为什么你可以看源码。

这里我建议，如果你想这样操作的话，可以在设置setAddToBackStack(false)的同时设置setNewActivity(true），这样就可以排除容器的影响了
